format = '$os-> $all'

[directory]
truncation_symbol = '…/'
use_os_path_sep = false

[nodejs]
symbol = '⬢ '

[docker_context]
disabled = true

[git_metrics]
disabled = false

[git_commit]
only_detached = false

[os]
disabled = false

[os.symbols]
Ubuntu = 'WSL '
Windows = 'WIN '

