name: npm package deploy

on: [workflow_call]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Deploy @latest version to npm
        if: startsWith(github.ref, 'refs/tags/')
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Update @next version
        if: startsWith(github.ref, 'refs/heads/')
        run: npm version prerelease --no-git-tag-version --preid "$GITHUB_RUN_NUMBER"

      - name: Deploy @next version to npm
        if: startsWith(github.ref, 'refs/heads/')
        uses: JS-DevTools/npm-publish@v1
        with:
          tag: next
          token: ${{ secrets.NPM_TOKEN }}
          check-version: false
