name: npm package CI/CD

on:
  workflow_call:

    inputs:

      deploy-npm:
        description: 'Deploy to npm.'
        default: true
        required: false
        type: boolean

      deploy-jsr:
        description: 'Deploy to JSR.'
        default: false
        required: false
        type: boolean

      node-versions:
        description: 'Stringified JSON object listing target Node versions.'
        default: '22'
        required: false
        type: string

    secrets:

      NPM_TOKEN:
        description: 'NPM audit token, omit to skip deployment.'
        required: true

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-versions) }}

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update npm
        run: npm i -g npm@latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Audit
        run: npm audit --omit=dev

      - name: Install packages
        run: npm ci

      - name: Test
        run: npm test

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          directory: coverage

  deploy:

    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.event_name == 'push'

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Update npm
        run: npm i -g npm@latest

      - uses: actions/checkout@v4

      - name: Install packages
        run: npm ci

      - name: Deploy @latest version to npm
        if: startsWith(github.ref, 'refs/tags/') && inputs.deploy-npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Deploy @latest version to JSR
        if: startsWith(github.ref, 'refs/tags/') && inputs.deploy-jsr
        run: npx jsr publish --provenance

      - name: Update @next version
        if: startsWith(github.ref, 'refs/heads/') && inputs.deploy-npm
        run: npm version prerelease --no-git-tag-version --preid "$GITHUB_RUN_NUMBER"

      - name: Deploy @next version to npm
        if: startsWith(github.ref, 'refs/heads/') && inputs.deploy-npm
        uses: JS-DevTools/npm-publish@v3
        with:
          tag: next
          token: ${{ secrets.NPM_TOKEN }}
          check-version: false
